DROP DATABASE IF EXISTS projeto_cobol;
CREATE DATABASE projeto_cobol;
USE projeto_cobol;

CREATE TABLE CLIENTES (
    CLI_ID INTEGER NOT NULL,
    CLI_NOME VARCHAR(30) NOT NULL,
    CLI_SALDO DECIMAL(9,0) NOT NULL,
    DT_ATUALIZACAO DATE,
    PRIMARY KEY (CLI_ID)
);

CREATE TABLE TRANSACOES (
    TRX_ID INTEGER NOT NULL,
    CLI_ID INTEGER NOT NULL,
    TRX_TIPO CHAR(1) NOT NULL,
    TRX_VALOR DECIMAL(9,0) NOT NULL,
    DT_PROCESSAMENTO DATE,
    PRIMARY KEY (TRX_ID)
);

CREATE TABLE ERROS_PROCESSAMENTO (
    ID_ERRO INTEGER AUTO_INCREMENT,
    CLI_ID INTEGER,
    DESCRICAO_ERRO VARCHAR(100),
    DT_OCORRENCIA TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ID_ERRO)
);

INSERT INTO CLIENTES
VALUES
(123,'JOAO SILVA',10000,CURDATE()),
(456,'MARIA SOUZA',25000,CURDATE()),
(789,'CARLOS PEREIRA',5000,CURDATE());

INSERT INTO TRANSACOES
VALUES
(10,123,'C',500,CURDATE()),
(20,123,'D',200,CURDATE()),
(30,456,'D',1000,CURDATE());

SELECT * FROM CLIENTES;
SELECT * FROM TRANSACOES;
SELECT * FROM ERROS_PROCESSAMENTO;
